# ##########################################

# Name der toml-Datei
dateiname = "halloween"

# Titel des Textes
titel = "Halloween"

# Quelle des Textes
quelle = "Klexikon"

# Hier kommt der Text
text = """
Dies ist ein Text von Klexikon - das Kinderlexikon

Das Fest Halloween ist schon sehr alt und wird jedes Jahr am 31. Oktober gefeiert. 
Das ist der Abend vor dem 1. November, also vor Allerheiligen. 
Der Name „Halloween“ kommt aus dem Englischen und ist eine Abkürzung für „All Hallows‘ Evening“. 
Übersetzt bedeutet das: „der Abend vor Allerheiligen“.  

Eigentlich kommt Halloween aus Irland, also aus Europa. 
Dort feierten die Einwohner Irlands, die Kelten, schon vor vielen Hundert Jahren dieses Fest. 
Sie glaubten, dass am Abend des 31. Oktobers die Toten auf die Erde zurückkehrten, um den Lebenden Streiche zu spielen. 
Deswegen sind die meisten Halloweenkostüme gruselig. 
Die Kelten hofften, dass die Toten dann an ihnen vorbeigehen und sie nicht als Lebende erkennen.  

Das Fest wurde dann in den USA beliebt. 
Es ist dort ähnlich wichtig wie woanders Fastnacht. 
Um das Jahr 2000 kam Halloween langsam auch zu uns. 
Manche Leute mögen es, weil sie sonst keine eigenen Traditionen mehr im Herbst haben.  

Wie feiert man Halloween?  

Bisher war das Gruselfest vor allem in den USA sehr beliebt. 
Inzwischen feiern auch viele Menschen in Deutschland Halloween. 
Besonders Kindern macht es Spass, sich als Hexen und Geister zu verkleiden und andere zu erschrecken. 
Sie gehen dann abends von Haustüre zu Haustüre und klingeln. 
Wenn jemand aufmacht, rufen sie „Süsses, sonst gibt’s Saures!“. 
Meistens bekommen die Kinder dann Süßigkeiten.  

Besonders beliebt ist auch die Kürbislaterne, die oft schon an den Tagen vor Halloween hergestellt wird. 
Dazu höhlt man einen Kürbis aus und schnitzt ein Gesicht hinein. 
Dann legt man eine Kerze in den Kürbis und kann ihn in den Garten oder auf einen Balkon stellen. 
Damit man das ausgehöhlte Fruchtfleisch nicht wegwerfen muss, kann man daraus eine Kürbissuppe kochen.  

In den USA ist es auch üblich, dass junge Leute zu Halloween-Partys einladen. 
Man bittet die Gäste, in einem passenden Kostüm zu kommen. 
Sie spielen dann Spiele oder erzählen einander gruselige Geschichten. 
"""

# Fragen zum Text (von KI erzeugt)
fragen = """
<h2>Fragen</h2>
<p>
<ol>
    <li>Wann wird Halloween gefeiert?</li>
    <li>Was bedeutet der Name "Halloween" auf Deutsch?</li>
    <li>Woher kommt Halloween ursprünglich?</li>
    <li>Wer sind die Kelten?</li>
    <li>Was glaubten die Kelten über den 31. Oktober?</li>
    <li>Warum sind die meisten Halloweenkostüme gruselig?</li>
    <li>Wann kam Halloween nach Deutschland?</li>
    <li>Wie feiern Kinder Halloween in Deutschland?</li>
    <li>Was rufen die Kinder an den Haustüren?</li>
    <li>Was ist eine Kürbislaterne?</li>
    <li>Was macht man mit dem Fruchtfleisch des Kürbisses?</li>
    <li>Was ist in den USA auf Halloween-Partys üblich?</li>
</ol>
</p>
"""

# Antworten zu den Fragen
antworten = """
<h2>Antworten</h2>
<p>
    <details>
        <ol>
            <li>Wann wird Halloween gefeiert? <br>
                Halloween wird jedes Jahr am 31. Oktober gefeiert.</li>
            <li>Was bedeutet der Name "Halloween" auf Deutsch? <br>
                "Halloween" bedeutet "der Abend vor Allerheiligen".</li>
            <li>Woher kommt Halloween ursprünglich? <br>
                Halloween kommt ursprünglich aus Irland.</li>
            <li>Wer sind die Kelten? <br>
                Die Kelten sind eine Gruppe von Menschen, die in Europa lebten und dieses Fest feierten.</li>
            <li>Was glaubten die Kelten über den 31. Oktober? <br>
                Die Kelten glaubten, dass die Toten an diesem Abend zurückkehrten.</li>
            <li>Warum sind die meisten Halloweenkostüme gruselig? <br>
                Die Kostüme sind gruselig, damit die Toten die Lebenden nicht erkennen.</li>
            <li>Wann kam Halloween nach Deutschland? <br>
                Halloween kam ungefähr um das Jahr 2000 nach Deutschland.</li>
            <li>Wie feiern Kinder Halloween in Deutschland? <br>
                Kinder verkleiden sich und gehen von Tür zu Tür.</li>
            <li>Was rufen die Kinder an den Haustüren? <br>
                Sie rufen "Süsses, sonst gibt’s Saures!".</li>
            <li>Was ist eine Kürbislaterne? <br>
                Eine Kürbislaterne ist ein ausgehöhlter Kürbis mit einer Kerze darin.</li>
            <li>Was macht man mit dem Fruchtfleisch des Kürbisses? <br>
                Man kann daraus eine Kürbissuppe kochen.</li>
            <li>Was ist in den USA auf Halloween-Partys üblich? <br>
                Es ist üblich, dass Gäste in Kostümen zu Partys eingeladen werden.</li>
        </ol>
    </details>
</p>
"""

# Rückmeldung der KI
ki_antwort = """### Gedanken zur Erstellung der Fragen

Ich werde Fragen zu verschiedenen Aspekten des Textes formulieren. Die Fragen sollen sich auf die wichtigsten Informationen und Details des Textes konzentrieren, um sicherzustellen, dass die Schüler den Inhalt genau lesen und darüber nachdenken. Ich werde Fragen zu Themen wie dem Ursprung von Halloween, den Traditionen, den Feiern und den Bräuchen stellen. Dabei werde ich darauf achten, dass die Fragen klar und einfach formuliert sind.

### Fragen in HTML-Liste

```html
<h2>Fragen</h2>
<p>
<ol>
    <li>Wann wird Halloween gefeiert?</li>
    <li>Was bedeutet der Name "Halloween" auf Deutsch?</li>
    <li>Woher kommt Halloween ursprünglich?</li>
    <li>Wer sind die Kelten?</li>
    <li>Was glaubten die Kelten über den 31. Oktober?</li>
    <li>Warum sind die meisten Halloweenkostüme gruselig?</li>
    <li>Wann kam Halloween nach Deutschland?</li>
    <li>Wie feiern Kinder Halloween in Deutschland?</li>
    <li>Was rufen die Kinder an den Haustüren?</li>
    <li>Was ist eine Kürbislaterne?</li>
    <li>Was macht man mit dem Fruchtfleisch des Kürbisses?</li>
    <li>Was ist in den USA auf Halloween-Partys üblich?</li>
</ol>
</p>
```

### Fragen und Antworten in HTML-Liste

```html
<h2>Antworten</h2>
<p>
    <details>
        <ol>
            <li>Wann wird Halloween gefeiert? <br>
                Halloween wird jedes Jahr am 31. Oktober gefeiert.</li>
            <li>Was bedeutet der Name "Halloween" auf Deutsch? <br>
                "Halloween" bedeutet "der Abend vor Allerheiligen".</li>
            <li>Woher kommt Halloween ursprünglich? <br>
                Halloween kommt ursprünglich aus Irland.</li>
            <li>Wer sind die Kelten? <br>
                Die Kelten sind eine Gruppe von Menschen, die in Europa lebten und dieses Fest feierten.</li>
            <li>Was glaubten die Kelten über den 31. Oktober? <br>
                Die Kelten glaubten, dass die Toten an diesem Abend zurückkehrten.</li>
            <li>Warum sind die meisten Halloweenkostüme gruselig? <br>
                Die Kostüme sind gruselig, damit die Toten die Lebenden nicht erkennen.</li>
            <li>Wann kam Halloween nach Deutschland? <br>
                Halloween kam ungefähr um das Jahr 2000 nach Deutschland.</li>
            <li>Wie feiern Kinder Halloween in Deutschland? <br>
                Kinder verkleiden sich und gehen von Tür zu Tür.</li>
            <li>Was rufen die Kinder an den Haustüren? <br>
                Sie rufen "Süsses, sonst gibt’s Saures!".</li>
            <li>Was ist eine Kürbislaterne? <br>
                Eine Kürbislaterne ist ein ausgehöhlter Kürbis mit einer Kerze darin.</li>
            <li>Was macht man mit dem Fruchtfleisch des Kürbisses? <br>
                Man kann daraus eine Kürbissuppe kochen.</li>
            <li>Was ist in den USA auf Halloween-Partys üblich? <br>
                Es ist üblich, dass Gäste in Kostümen zu Partys eingeladen werden.</li>
        </ol>
    </details>
</p>
```"""

