# ##########################################

# Name der toml-Datei
dateiname = "test"

# Titel des Textes
titel = "test"

# Quelle des Textes
quelle = ""

# Hier kommt der Text
text = """
Die Jüdische Gemeinde in Dornum gab es rund 300 Jahre lang. 
Sie begann im 17. Jahrhundert und hörte am 8. März 1940 auf.  
Im Jahr 1925 lebten in Dornum viele Juden. 
Sie machten 7,3 % der Bevölkerung aus. 
Das war der höchste Anteil in Ostfriesland, ausser in Neustadtgödens.  
Die ersten Juden kamen nach dem Dreißigjährigen Krieg nach Dornum. 
1626 bekamen sie das Recht von Graf Rudolf Christian, eigene Schutzbriefe zu machen. 
Mit diesen Briefen konnten sie sicher in Dornum leben.  
Die Juden nahmen am Leben im Dorf teil. 
Sie waren Mitglieder in verschiedenen Vereinen.   
Ab 1933 wurden die Juden jedoch ausgeschlossen und verfolgt. 
Viele von ihnen emigrierten, das bedeutet, sie mussten in andere Länder ziehen. 
Im Holocaust, das war eine sehr schlimme Zeit, wurden über 50 % der jüdischen Menschen in Dornum ermordet.   
Die überlebenden Juden kehrten nicht zurück nach Dornum. 
Die Synagoge, das ist das Gebetshaus der Juden, wurde bis 1990 als Möbel-Lager genutzt.   
1990 gründete sich ein Verein mit dem Namen „Synagoge Dornum“. 
Dieser Verein möchte die Synagoge schützen und wieder schön machen. 
Sie kümmern sich auch um den jüdischen Friedhof und wollen eine Ausstellung über die jüdische Geschichte in Dornum zeigen.  
Im Jahr 1991 wurde die Synagoge mit Hilfe von Spendengeldern und der Gemeinde Dornum repariert. 
Jetzt ist sie ein Ort zum Gedenken und zum Informieren über die jüdische Geschichte.  
"""

# Fragen zum Text (von KI erzeugt)
fragen = """xxx"""

# Antworten zu den Fragen
antworten = """xxx"""

# Rückmeldung der KI
ki_antwort = """xxx"""

