# ##########################################

# Name der toml-Datei
dateiname = "tttesssttt"

# Titel des Textes
titel = "test"

# Quelle des Textes
quelle = "tset"

# Hier kommt der Text
text = """
Wer nicht flüssig lesen kann, arbeitet sich mühsam Wort für Wort durch einen Text und schafft es kaum, Zusammenhänge zu erfassen. 
Diese Schülerinnen und Schüler empfinden das Lesen als permanente Anstrengung und Bedrohung — so schließt sich ein Teufelskreis des Nichtlesens.

Die Literaturdidaktikerin Prof. Dr. Cornelia Rosebrock von der Goethe-Universität Frankfurt am Main bringt es auf den Punkt: 
Wer nur unter Anstrengungen lesen kann, für den wird Lesen zum „roten Tuch“. 
Und je weniger man liest, desto größer werden die Defizite. 

Deshalb ist es wichtig, die Lesefähigkeit von Kindern und Jugendlichen systematisch zu fördern. 
Denn Kindern, die nicht flüssig lesen lernen, werden Chancen verbaut. 
Lesen ist eine Schlüsselkompetenz, die viele Lebensbereiche öffnet: 
In der Schule ist Textverständnis in allen Fächern die Voraussetzung dafür, dass man dem Unterricht folgen kann. 
Es ist die Grundlage für die Qualifizierung in Ausbildung und Beruf und Basis der Teilhabe am gesellschaftlichen und kulturellen Leben.
"""

# Fragen zum Text (von KI erzeugt)
fragen = """xxx"""

# Antworten zu den Fragen
antworten = """xxx"""

# Rückmeldung der KI
ki_antwort = """xxx"""

